# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd446fca99dd7086fe0806d5dbb06169c445b9a5a7ce532654ef9927f22fc10dccf2151fb6f935d53641b6bd4ccc1243605d77984487fd766555973e7ad70ce5

test:
  secret_key_base: 2839835ade96d2123683045a7bfe1e7c7a9d318cddc7082973a4faca51b7a7b4fad3bb9e0a7f49cb3b04389c56aba58fdfc00fa6e3e96ff09373c32ac5172736

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
